### ISSUE TITLE
Error Wiki page

### ISSUE THREAD

**Issue by hugocc** [rorx/redmine_wiki_sql#8]
Hi, please help me, show it error

Error executing the sql macro (undefined method `num_rows' for #Mysql2::Result:0x7f734bb8d588)

It is my sql en wiki page
# Wiki

{{sql( select id as 'ID', subject as 'Subject' from redmine.issues where id between 1 and 10)}}

**Comment by volkswagner** [comment]
I get same error with any query.

I realize this plugin has not been updated in a couple years. I guess it's not
compatible with current version.

Environment:
  Redmine version                2.5.2.stable.13335
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem  
Redmine plugins:
  redmine_app__space             1.0.3
  redmine_app_timesheets         1.4.11
  redmine_loader                 0.3b
  redmine_omniauth_google        0.0.1
  redmine_wiki_sql               0.0.1

**Comment by biiont** [comment]
Got same error.

Looks like interface for ActiveRecord have changed thus breaking this plugin. I have adopted redmine_wiki_sql code to work with Redmine 3.0.1 and ActiveRecord 4.2.0.

Currently have posted pull request to the developer. Until then try to use my variation of the plugin -- https://github.com/biiont/redmine_wiki_sql
